my:
  defaultPageSize: 10
  savePath: D:/savePath/
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 1800000
      maximum-pool-size: 15
      minimum-idle: 5
      pool-name: DatebookHikariCP
    password: ''
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/qcode?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
  freemarker:
    charset: utf-8
    suffix: .html
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true

